openapi: 3.0.0

info:
  version: 3.0.x-oas3
  title: AnimeGame
  description: Card game to chill with friends.

servers:
  - url: http://anigame
  - url: https://virtserver.swaggerhub.com/Speedruners/AniGame/3.0.x

paths:
  /registration:
    post:
      summary: Adds a new user
      requestBody:
        description: registration
        required: true
        content:
            application/json:
              schema:
                properties:
                  email:
                    type: string
                    example: vasaTop123@meta.ua
                  username:
                    type: string
                    example: Darkstyle
                  password:
                    type: string
                    example: 12365478
                  gender:
                    type: string
                    enum: [male,female]

      responses:
        '200':
            description: successful registered
        '400':
            description: nickname or email alredy exist

  /login:
    description: login existing user
    post:
      summary: login existing user
      requestBody:
        content:
          aplication/json:
            schema:
              properties:
                email:
                  type: string
                  example: vasaTop123@meta.ua
                password:
                  type: string
                  example: Vnstop
      responses:
        '200':
          description: successful login
        '401':
          description: Unauthorized
  /profile/{id}:
    description: :Return data for user(id) profile
    get:
        parameters:
          - in: path
            name: id
            schema:
              type: integer
            required: true
        responses:
          '200':
            description: successful
            content:
              application/json:
                schema:
                  properties:
                    user_id:
                      type: integer
                    userName:
                      type: string
                      example: Darkstyle
                    email:
                      type: string
                      example: vasaTop123@meta.ua
                    gender:
                        type: string
                        enum: [male,female]
                    image_url:
                      type: string
                      example: https://pm1.narvii.com/7303/9baf944e3ede78430e21b79547c00878d7691437r1-448-454v2_hq.jpg
                    achievements:
                      type: array
                      items:
                        $ref: '#/components/schemas/Achievement'
          '401':
            description: need Authorization
          '404':
            description: user didn't found

  /profile/{id}/change/password:
    description: change user password
    put:
      summary: request for change password
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        content:
          aplication/json:
            schema:
              properties:
                previous_password:
                  type: string
                  minLength: 8
                new_password:
                  type: string
                  minLength: 8
      responses:
        '200':
          description:  password changed successful
        '403':
          description: you cannot change another user password

  /profile/{id}/change:
     put:
      summary: request for change image or username
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        content:
          aplication/json:
            schema:
              properties:
                image_url:
                  type: string
                username:
                  type: string
      responses:
        '200':
          description:  data changed successful
        '401':
          description:  need Authorization
        '400':
          description: username is not available

  /game/start:
    description: Function for add user in queue (need  retrieve user rating from db and add user with rating t0 queue)
    post:
        requestBody:
          content:
            aplication/json:
              schema:
                properties:
                  userId:
                    type: integer
        responses:
          '200':
            description: successful added to queue (redirect to page with game)
            content:
               application/json:
                schema:
                  properties:
                    redirect:
                      type: string
                      example: http://anigame/game/{gameId}/
          '401':
            description: Unauthorized
          '500':
            description: Smf went wrong -)


  /game/{gameId}/:
    description: Send question to oponent
    post:
      parameters:
        - in: path
          name: gameId
          schema:
            type: integer
          required: true
      requestBody:
        content:
          aplication/json:
            schema:
              properties:
                userId:
                  type: integer

      responses:
        '200':
            description: question sended successfuly
            content:
              aplication/json:
                schema:
                  properties:
                    ArrayCards:
                      type: array
                      items:
                        $ref: '#/components/schemas/Card'
                    Enemy_guest_character:
                        $ref: '#/components/schemas/Card'


  /game/{gameId}/sendquestion:
    description: Send question to oponent
    post:
      parameters:
        - in: path
          name: gameId
          schema:
            type: integer
          required: true
      requestBody:
        content:
          aplication/json:
            schema:
              properties:
                userId:
                  type: integer
                text:
                  type: string
      responses:
        '200':
            description: question sended successfuly
            content:
              aplication/json:
                schema:
                  properties:
                    text:
                      type: string

  /game/{gameId}/sendrequest:
     description: Send request to server (check for victory)
     post:
       parameters:
         - in: path
           name: gameId
           schema:
             type: integer
           required: true
       requestBody:
         content:
           aplication/json:
             schema:
               properties:
                  user_id:
                    type: integer
                  cardsArray:
                    type: array
                    items:
                      $ref: '#/components/schemas/Card'
       responses:
         '200':
             description: request sended successfuly
             content:
               aplication/json:
                 schema:
                   properties:
                     isWin:
                      type: boolean




components:
  schemas:
    User:
      type: object
      properties:
        user_id:
          type: integer
        userName:
          type: string
          example: Darkstyle
        email:
          type: string
          example: vasaTop123@meta.ua
        password:
          type: string
          minimum: 8
          example: 123654df
        gender:
            type: string
            enum: [male,female]

    Character:
      type: object
      properties:
        characterName:
          type: string
        country:
          type: string
        is_alive:
          type: boolean
        is_good:
          type: boolean
        image:
          type: string
    Card:
      type: object
      properties:
        card_id:
          type: integer
        character:
          $ref: '#/components/schemas/Character'
        is_active:
          type: boolean
    Achievement:
      type: object
      properties:
        achive_id:
          type: integer
          example: 1
        achive_name:
          type: string
          example: win first game
        experience:
          type: integer
          example: 10
        image_url:
          type: string
          example: https://img2.freepng.ru/20171128/d7f/gold-cup-with-laurel-leaves-png-clipart-image-5a1d43eae89be9.1769932315118673709528.jpg