"""empty message

Revision ID: b8c03de17a54
Revises: ce250efc6932
Create Date: 2022-08-15 12:28:56.708285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c03de17a54'
down_revision = 'ce250efc6932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_block_list', sa.Column('type', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_block_list', 'type')
    # ### end Alembic commands ###
